### ISSUE TITLE
Error in pend_control.m

### ISSUE THREAD

**Issue by jdanielhoyos** [jbramburger/data-clf#1]
Hello! Thanks for help. When I run pend_control.m, it says 
Identified control input: 
u(x) = You have NaNs in model (learn to debug)
Error using  * 
Multiplying NaN with an SDPVAR makes no sense.

Error in LyapKoopman (line 147)
sdisplay(value(cu).'*xmons)
Do you any suggestion?
Also, I noted line 102 says x = sdpvar(3,1); % 2D state variable, why if it is 2d state variable its sdpvar(3,1); ?
Thanks!

**Comment by jbramburger** [comment]
Hello jdanielhoyos,

It looks like you figured this out. Is that true?

The reason you're seeing that is because the data used to seed the method is randomly generated. Every once in a while you'll generate bad data and won't get a sufficient approximation of the Koopman operator, leading to a dud run.

Happy to chat anytime!

Jason

**Comment by jdanielhoyos** [comment]
It was because I havent installed mosak properyl with the license. But Im still curious, why we have  x = sdpvar(3,1);, and the control u is in terms of x1 x2 x3, what are those variables? @jbramburger 
Ty
